name: iOS Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout del c√≥digo
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Dar permisos al Gradlew
        run: chmod +x gradlew

      - name: Construir Proyecto
        # Este comando es el "maestro", construye todo lo de iOS disponible
        run: ./gradlew assembleDebug

      - name: Buscar y Subir el instalador
        uses: actions/upload-artifact@v4
        with:
          name: ios-app-artifact
          # Buscamos cualquier cosa que parezca un ejecutable de iOS
          path: |
            **/build/bin/iosArm64/debugFramework/*.framework
            **/build/outputs/ios/**/*.zip
            **/build/outputs/apple/**/*.zip
          if-no-files-found: warn